from dataclasses import dataclass

import sqlite3

from linechef.poketype import Poketype

SOUND_BASED_MOVES = set([
    "Growl",
    "Roar",
    "Sing",
    "Supersonic",
    "Screech",
    "Snore",
    "Perish Song",
    "Heal Bell",
    "Uproar",
    "Hyper Voice",
    "Metal Sound",
    "Grass Whistle",
    "Howl",
    "Bug Buzz",
    "Chatter",
    "Round",
    "Echoed Voice",
    "Relic Song",
    "Snarl",
    "Noble Roar",
    "Disarming Voice",
    "Parting Shot",
    "Boomburst",
    "Confide",
    "Sparkling Aria",
    "Clanging Scales",
    "Clangorous Soulblaze",
    "Clangorous Soul",
    "Overdrive",
    "Eerie Spell"
])

CONTACT_MOVES = set([
    "Accelerock",
    "Acrobatics",
    "Aerial Ace",
    "Anchor Shot",
    "Aqua Jet",
    "Aqua Step",
    "Aqua Tail",
    "Arm Thrust",
    "Assurance",
    "Astonish",
    "Avalanche",
    "Axe Kick",
    "Behemoth Bash",
    "Behemoth Blade",
    "Bide",
    "Bind",
    "Bite",
    "Bitter Blade",
    "Blaze Kick",
    "Body Press",
    "Body Slam",
    "Bolt Beak",
    "Bolt Strike",
    "Bounce",
    "Branch Poke",
    "Brave Bird",
    "Breaking Swipe",
    "Brick Break",
    "Brutal Swing",
    "Bug Bite",
    "Bullet Punch",
    "Catastropika",
    "Ceaseless Edge",
    "Chip Away",
    "Circle Throw",
    "Clamp",
    "Close Combat",
    "Collision Course",
    "Comet Punch",
    "Comeuppance",
    "Constrict",
    "Counter",
    "Covet",
    "Crabhammer",
    "Cross Chop",
    "Cross Poison",
    "Crunch",
    "Crush Claw",
    "Crush Grip",
    "Cut",
    "Darkest Lariat",
    "Dig",
    "Dire Claw",
    "Dive",
    "Dizzy Punch",
    "Double-Edge",
    "Double Hit",
    "Double Iron Bash",
    "Double Kick",
    "Double Shock",
    "Double Slap",
    "Dragon Ascent",
    "Dragon Claw",
    "Dragon Hammer",
    "Dragon Rush",
    "Dragon Tail",
    "Draining Kiss",
    "Drain Punch",
    "Drill Peck",
    "Drill Run",
    "Dual Chop",
    "Dual Wingbeat",
    "Dynamic Punch",
    "Electro Drift",
    "Endeavor",
    "Extreme Speed",
    "Facade",
    "Fake Out",
    "False Surrender",
    "False Swipe",
    "Feint Attack",
    "Fell Stinger",
    "Fire Fang",
    "Fire Lash",
    "Fire Punch",
    "First Impression",
    "Fishious Rend",
    "Flail",
    "Flame Charge",
    "Flame Wheel",
    "Flare Blitz",
    "Flip Turn",
    "Floaty Fall",
    "Fly",
    "Flying Press",
    "Focus Punch",
    "Force Palm",
    "Foul Play",
    "Frustration",
    "Fury Attack",
    "Fury Cutter",
    "Fury Swipes",
    "Gear Grind",
    "Giga Impact",
    "Glaive Rush",
    "Grass Knot",
    "Grassy Glide",
    "Guillotine",
    "Gyro Ball",
    "Hammer Arm",
    "Hard Press",
    "Headbutt",
    "Head Charge",
    "Headlong Rush",
    "Head Smash",
    "Heart Stamp",
    "Heat Crash",
    "Heavy Slam",
    "High Horsepower",
    "High Jump Kick",
    "Hold Back",
    "Horn Attack",
    "Horn Drill",
    "Horn Leech",
    "Hyper Drill",
    "Hyper Fang",
    "Ice Ball",
    "Ice Fang",
    "Ice Hammer",
    "Ice Punch",
    "Ice Spinner",
    "Infestation",
    "Iron Head",
    "Iron Tail",
    "Jaw Lock",
    "Jet Punch",
    "Jump Kick",
    "Karate Chop",
    "Knock Off",
    "Kowtow Cleave",
    "Lash Out",
    "Last Resort",
    "Leaf Blade",
    "Leech Life",
    "Lick",
    "Liquidation",
    "Low Kick",
    "Low Sweep",
    "Lunge",
    "Mach Punch",
    "Malicious Moonsault",
    "Megahorn",
    "Mega Kick",
    "Mega Punch",
    "Metal Claw",
    "Meteor Mash",
    "Mighty Cleave",
    "Mortal Spin",
    "Multi-Attack",
    "Needle Arm",
    "Night Slash",
    "Nuzzle",
    "Outrage",
    "Payback",
    "Peck",
    "Petal Dance",
    "Phantom Force",
    "Plasma Fists",
    "Play Rough",
    "Pluck",
    "Poison Fang",
    "Poison Jab",
    "Poison Tail",
    "Population Bomb",
    "Pounce",
    "Pound",
    "Power Trip",
    "Power-Up Punch",
    "Power Whip",
    "Psyblade",
    "Psychic Fangs",
    "Psyshield Bash",
    "Pulverizing Pancake",
    "Punishment",
    "Pursuit",
    "Quick Attack",
    "Rage",
    "Rage Fist",
    "Raging Bull",
    "Rapid Spin",
    "Razor Shell",
    "Retaliate",
    "Return",
    "Revenge",
    "Reversal",
    "Rock Climb",
    "Rock Smash",
    "Rolling Kick",
    "Rollout",
    "Sacred Sword",
    "Scratch",
    "Searing Sunraze Smash",
    "Seismic Toss",
    "Shadow Claw",
    "Shadow Force",
    "Shadow Punch",
    "Shadow Sneak",
    "Sizzly Slide",
    "Skitter Smack",
    "Skull Bash",
    "Sky Drop",
    "Sky Uppercut",
    "Slam",
    "Slash",
    "Smart Strike",
    "Smelling Salts",
    "Snap Trap",
    "Solar Blade",
    "Soul-Stealing 7-Star Strike",
    "Spark",
    "Spectral Thief",
    "Spin Out",
    "Spirit Break",
    "Steamroller",
    "Steel Roller",
    "Steel Wing",
    "Stomp",
    "Stomping Tantrum",
    "Stone Axe",
    "Storm Throw",
    "Strength",
    "Submission",
    "Sucker Punch",
    "Sunsteel Strike",
    "Supercell Slam",
    "Super Fang",
    "Superpower",
    "Surging Strikes",
    "Tackle",
    "Tail Slap",
    "Take Down",
    "Temper Flare",
    "Thief",
    "Thrash",
    "Throat Chop",
    "Thunder Fang",
    "Thunderous Kick",
    "Thunder Punch",
    "Trailblaze",
    "Triple Axel",
    "Triple Dive",
    "Triple Kick",
    "Trop Kick",
    "Trump Card",
    "U-turn",
    "Upper Hand",
    "V-create",
    "Veevee Volley",
    "Vine Whip",
    "Vise Grip",
    "Vital Throw",
    "Volt Tackle",
    "Wake-Up Slap",
    "Waterfall",
    "Wave Crash",
    "Wicked Blow",
    "Wild Charge",
    "Wing Attack",
    "Wood Hammer",
    "Wrap",
    "Wring Out",
    "X-Scissor",
    "Zen Headbutt",
    "Zing Zap",
    "Zippy Zap",
    "Shadow Strike"
])


@dataclass(frozen=True)
class Pokemove:
    movename: str
    damage_class: str
    target: str
    power: int
    accuracy: int
    priority: int
    poketype: Poketype
    flinch_chance: int
    ailment: str
    ailment_chance: int
    crit_rate: int
    stat: str
    stat_chance: int
    drain: int
    healing: int
    min_hits: int | None
    max_hits: int | None

    @staticmethod
    def get_pokemove_by_id(move_id: int | None) -> "Pokemove | None":
        if move_id is None:
            return None

        db = sqlite3.connect("db/rnb.db")
        db.row_factory = sqlite3.Row
        cursor = db.cursor()

        movedetails = cursor.execute(
            "SELECT * FROM pokemove WHERE id == (?)", (move_id,)).fetchone()

        if movedetails is None:
            breakpoint()

        movedict = dict(movedetails)
        movedict.pop("id")

        return Pokemove(**movedict)

    def get_priority(self) -> int:
        return self.priority

    def is_sound_based(self) -> bool:
        return self.movename in SOUND_BASED_MOVES

    def makes_contact(self) -> bool:
        return self.movename in CONTACT_MOVES
